### ISSUE TITLE
Bug of get An Account using method chartofaccounts()

### ISSUE THREAD

**Issue by MPTA** [Weble/ZohoBooksApi#105]
using code "ZohoBook::make()->chartofaccounts->get($id)" return below error:

ErrorException
PHP 8.2.8
10.31.0
Undefined array key "chartofaccount"

as i checked API files , thr API server will return chart of account with name "chart_of_account" but  method of Module.php file line 76 () $this->inflector->singularize($this->getResourceItemKey() will return "chartofaccount" key name.

please try to fix it . 

<img width="789" alt="Screenshot 1402-08-21 at 14 45 19" src="https://github.com/Weble/ZohoBooksApi/assets/40070445/70b868d6-0deb-4ad8-86ec-caad93f2e24e">

**Comment by Skullbock** [comment]
Hi, thanks for the report. 
Can you send a PR to fix this? There were similar fixes applied for other modules

Thanks!

**Comment by MPTA** [comment]
> Hi, thanks for the report. Can you send a PR to fix this? There were similar fixes applied for other modules
> 
> Thanks!

i am sorry, what is the mean of PR ?

**Comment by Skullbock** [comment]
Pull Request :-) basically you can submit the fix yourself!

**Comment by SlavaPWNZ** [comment]
@Skullbock Hi
Update VendorPayments too))
Now:
public function getName()
    {
        return 'payment';
    }
    
    
But need 'vendorpayment'

**Comment by Skullbock** [comment]
Hi @SlavaPWNZ and @MPTA

If you can, send us a PR with these two quick fixes, so we can merge them and release
Thanks!

**Comment by MPTA** [comment]
I found problem but could not fix it.

**Comment by Skullbock** [comment]
We've release 5.5.2 with a fix for both for you to test
