### ISSUE TITLE
How to create new contact address

### ISSUE THREAD

**Issue by bluec** [Weble/ZohoBooksApi#17]
I was looking to do a PR to enable [adding a new address to a contact](https://www.zoho.com/books/api/v3/#Contacts_Add_Additional_Address) but I am unsure of how this should be achieved. 

This [commit shows what I have done](https://github.com/bluec/ZohoBooksApi/commit/e2a775703b8f7b0c15957bbc89a30c5fd812a154), and it works, but somehow I feel that the Submodule architecture is designed for this type of functionality but I'm struggling to understand the design pattern and how to utilise it.

**Comment by Skullbock** [comment]
Hey, yes, submodule was born for that reason, but currently is only used to get data, not create it.
If you want to expand on that, feel free to do so.

Currently, if you extend Submodule instead of module, you get the same functionality, proxying from the parent class

```$contact->getAddresses()```
