### ISSUE TITLE
Problem with customerpayments and payment

### ISSUE THREAD

**Issue by ghost** [Weble/ZohoBooksApi#20]
In CustomerPayments.php line 33 :
Replace return 'payment'; by return 'customerpayments';
to make customerpayments->getList() not returning an error.

However, doing that makes customerpayments->get() returning an error

**Comment by ghost** [comment]
Module.php line 65 :
        //$data = $item[Inflector::singularize($this->getResourceKey())];
        
        if ($this->getResourceKey() == 'customerpayments') {
            $data = $item[Inflector::singularize('payment')];
        } else {
        $data = $item[Inflector::singularize($this->getResourceKey())];
        }

**Comment by Skullbock** [comment]
Just released 3.0.2.
The correct fix was to implement the ```getResourceKey()``` method in the  CustomerPayments Module
