### ISSUE TITLE
Settings/TaxGroups returns an error from Zoho

### ISSUE THREAD

**Issue by xrobau** [Weble/ZohoBooksApi#26]
var_dump($zoho->settings->taxgroups->getList()->toArray());

Zoho returns 'The HTTP method GET is not allowed for the requested resource'

**Comment by Skullbock** [comment]
Yeah, seems that you can only GET / CREATE / UPDATE / DELETE but not LIST.
The best way for this would be to override the getList method in the taxgroups module to throw an exception. What do you think?

[https://www.zoho.com/books/api/v3/#Taxes_Get_a_tax_group](https://www.zoho.com/books/api/v3/#Taxes_Get_a_tax_group)

**Comment by xrobau** [comment]
So, you ARE doing a get - with this:

```
string(48) "https://books.zoho.com/api/v3/settings/taxgroups"
array(2) {
  ["headers"]=>
  array(1) {
    ["Authorization"]=>
    string(86) "Zoho-oauthtoken 1000.blahblah"
  }
  ["query"]=>
  array(1) {
    ["organization_id"]=>
    string(9) "701433241"
  }
}
```

BUT! There is no way to get a list of them, according to their API. So I dunno what to do here.

Probably just close as can't fix?
