### ISSUE TITLE
Strange issue with Illuminate\Support\Collection

### ISSUE THREAD

**Issue by xrobau** [Weble/ZohoBooksApi#29]
Haven't looked into it, but in Modules\Module::getList(), the Laravel collection is crapping out on an empty array.  Recording it for further investigation later.

Here's the contents of $list, when asking for customerpayments (which, as this is a test org, has no payments) - it's an empty array:

```
array(4) {
  ["code"]=>
  int(0)
  ["message"]=>
  string(7) "success"
  ["customerpayments"]=>
  array(0) {
  }
  ["page_context"]=>
  array(8) {
    ["page"]=>
    int(1)
    ["per_page"]=>
    int(200)
    ["has_more_page"]=>
    bool(false)
    ["report_name"]=>
    string(17) "Payments Received"
    ["applied_filter"]=>
    string(15) "PaymentMode.All"
    ["custom_fields"]=>
    array(0) {
    }
    ["sort_column"]=>
    string(4) "date"
    ["sort_order"]=>
    string(1) "D"
  }
}
```

However, the Laravel Collection is trying to iterate over... SOMETHING. 

```[2019-11-24 21:14:41] local.ERROR: Undefined index: payment {"exception":"[object] (ErrorException(code: 0): Undefined index: payment at /root/billing/src/scrooge/vendor/webleit/zohobooksapi/src/Modules/Module.php:44)
[stacktrace]
#0 /root/billing/src/scrooge/vendor/webleit/zohobooksapi/src/Modules/Module.php(44): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /root/billing/src/scrooge/test.php(37): Webleit\\ZohoBooksApi\\Modules\\Module->getList()
#2 {main}
"}

   ErrorException  : Undefined index: payment

  at /root/billing/src/scrooge/vendor/webleit/zohobooksapi/src/Modules/Module.php:44
    40|     {
    41|         $list = $this->client->getList($this->getUrl(), null, $params);
    42|         var_dump($list);
    43|
  > 44|         $collection = new Collection($list[$this->getResourceKey()]);
    45|         $collection = $collection->mapWithKeys(function ($item) {
    46|             $item = $this->make($item);
    47|             return [$item->getId() => $item];
    48|         });

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
      /root/billing/src/scrooge/vendor/webleit/zohobooksapi/src/Modules/Module.php:44

  2   Webleit\ZohoBooksApi\Modules\Module::getList()
      /root/billing/src/scrooge/test.php:37
```

**Comment by xrobau** [comment]
I also noticed it with VendorCredits - when getName is defined in a module, something's confusing the mapWithKeys.

My gut feeling is that if $list[$thius->getResourceKey()] is empty, it should just return an empty collection, but I've spent zero brain time on this 8)

**Comment by Skullbock** [comment]
Hey, good catch, but it's actually a similar error to the one you've already fixed in other PRs

```$collection = new Collection($list[$this->getResourceKey()]);```

This check if the key exists in the array for the given module, and reads that.
In **customer payments** it tries to check the **payment** key, while it should check the ** customerpayments** key. 
We should implement the **getResourceKey** method correctly for that module. Same for VendorCredits
