### ISSUE TITLE
Cannot retrieve a recurring invoice

### ISSUE THREAD

**Issue by ghost** [Weble/ZohoBooksApi#41]
Hello,

When :
$invoice = $zohoBooks->recurringinvoices->get($line['Recurring Invoice ID']);

Get :
Notice: Undefined index: recurringinvoice in \vendor\webleit\zohobooksapi\src\Modules\Module.php

Got a solution ?
Thanks 

PS : Always on 2.2 beacause I don't success to generate Access Token

**Comment by Skullbock** [comment]
The fix was applied on 3.x

https://github.com/Weble/ZohoBooksApi/blob/develop/src/Modules/RecurringInvoices.php#L29

We don't update 2.x anymore, so either manually patch your version with the same fix, or move to 3.x as suggested :)
