### ISSUE TITLE
Composer Warnings

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoBooksApi#43]
`Deprecation Notice: Class Webleit\ZohoBooksApi\Models\Invoice\Expense located in ./vendor/webleit/zohobooksapi/src/Models/RecurringExpense/Expense.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by Skullbock** [comment]
Fixed in 3.3.3
Thanks for the catch!
