### ISSUE TITLE
$api->settings no longer works

### ISSUE THREAD

**Issue by xrobau** [Weble/ZohoBooksApi#49]
I finally bit the bullet and upgraded my code to 4.3, and have discovered that settings no longer works - it is the only thing that implements 'ProvidesModules' (which I assume has broken at some time in the past), and now errors with this:

```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Return value of Webleit\ZohoBooksApi\ZohoBooks::__get() must be an instance of Webleit\ZohoBooksApi\Modules\Module, instance of Webleit\ZohoBooksApi\Modules\Settings returned

  at /usr/local/scrooge/vendor/webleit/zohobooksapi/src/ZohoBooks.php:87
    83|     }
    84|
    85|     public function __get(string $name): Modules\Module
    86|     {
  > 87|         return $this->createModule($name);
    88|     }
    89|
    90|     public function getClient(): Client
    91|     {

  Exception trace:

  1   Webleit\ZohoBooksApi\ZohoBooks::__get("settings")
      /usr/local/scrooge/err.php:20
```

Removing the Modules\Module return fixes it.  I am not sure how you want to fix this - Should Modules\Settings implement \Webleit\ZohoBooksApi\Contracts\Module or should you have another ModuleInterface somewhere else?

**Comment by Skullbock** [comment]
Hey @xrobau thanks for the notice.
I've implemented a fix and release a new version ;)
