### ISSUE TITLE
Feature: Remove need for tightenco/collect

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoBooksApi#55]
With the release of Laravel 8 Laravel now officially maintains illuminate/collections [https://github.com/illuminate/collections]

The tightenco library is now deprecated (https://github.com/tighten/collect#deprecated-with-the-separation-of-illuminates-collections-package-collect-is-no-longer-necessary-tada--we-will-maintain-it-for-the-80-and-90-releases-of-laravel-for-the-convenience-of-package-maintainers-and-will-stop-mirroring-new-major-versions-after-90-but-keep-the-existing-package-here-for-continued-support)

What should probably be done is a new release of this library (new major version) that uses illuminate/collections. Then update the class references. Most changes that happen in the tightenco release can be merged into the illuminate/collections release

**Comment by Skullbock** [comment]
@tm1000 it's in my todo list for all the packages where i use tightenco's library.
I'll keep this issue up so you can be notified when i switch ;)

**Comment by Skullbock** [comment]
@tm1000 pushed 4.4.0 with this change ;)
