### ISSUE TITLE
invoices->getCreditsApplied($id) doesn't work because of 'ucfirst'

### ISSUE THREAD

**Issue by xrobau** [Weble/ZohoBooksApi#56]
```
$zi = $books->invoices->getList(["customer_id" => $ip->getBooksCustomerId(), "last_modified_time" => $lmt]);
foreach ($zi as $z) {
    $credits = $books->invoices->getCreditsApplied($z->invoice_id);
}
```

Results in:
1) Tests\Unit\Cleanup::testCleanup
Error: Class '\Webleit\ZohoBooksApi\Models\Invoice\Creditsapplied' not found

Copying/Renaming CreditsApplied.php to Creditsapplied.php in Models and Models/Invoice fixes it, but that's kinda poop. I'm also guessing that possibly other things that are CamelCased may also be broken?

**Comment by xrobau** [comment]
I also discovered that it's only returning a single item in the collection, even if there are multiple credit notes assigned to the invoice.

**Comment by Skullbock** [comment]
Hi @xrobau i've pushed 4.4.1 that fixes this.

Issue was that on macosx (my OS) it's "smart enough" to get "CreditsApplied" instead of "Creditsapplied" as a class, while probably linux or windows don't do that.

The fix forces the class itself. Hope it helps

**Comment by Skullbock** [comment]
@xrobau was this fixed?

**Comment by xrobau** [comment]
Eek, sorry, I missed the ping on this one. I'll spin up some tests and get back to you shortly.  Thanks to @tm1000 for poking me about this.

**Comment by xrobau** [comment]
Yep, no longer getting upset about ucfirst! Sorry for being so slow.

**Comment by Skullbock** [comment]
No worries, was cleaning up issues :)
