### ISSUE TITLE
v4 Region for US is .us instead of .com

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoBooksApi#67]
When the region is US the suffix should be .com. Right now it's .us. I resolved this by `setRegion('com')`

**Comment by Skullbock** [comment]
You are right. Best way for me would be to change the constant value, what do you say? It's only used for that...

**Comment by tm1000** [comment]
Yes I think that's fine.

**Comment by Skullbock** [comment]
I fixed it differently, see attached commit.
This fix is included in v5.0.2
