### ISSUE TITLE
what is the best cache?

### ISSUE THREAD

**Issue by romerpt** [Weble/ZohoBooksApi#70]
Hi there,

I would like to know what is the best module for cache that you would recommend, and if there is any practical example of how to implement it.

Thanks in advanced.

**Comment by Skullbock** [comment]
Hi @vitoraos it really depends on you project's stack and the volume of the requests you will be doing. Any psr6 compatible driver is good. 

For me, I tend to rely on symfony's cache drivers

https://symfony.com/doc/current/components/cache.html#basic-usage-psr-6

The simplest one to use is the file system cache driver, and for intensive applications or distibuted one I switch to the redis one. 

Cheers
