### ISSUE TITLE
Get single sales order issue

### ISSUE THREAD

**Issue by CodingMonkTech** [Weble/ZohoBooksApi#8]
As per new Zoho Dumentation

We need to pass salesorder_id as parameter to get single sales order salesorder_id is required parameter. so we need to change things into either Client.php or Module.php

**Comment by Skullbock** [comment]
Hi @CodingMonkTech , you should already be able to do that by calling

```
$salesOrders = $zohoBooks->salesorders->get('salesorders_id');
```
