### ISSUE TITLE
Add ability to pass a filter and to send a list of unpaid invoices

### ISSUE THREAD

**Issue by GameGamer43** [Weble/ZohoBooksApi#92]
When emailing a statement you can pass a filter (Status.Outstanding, Status.All)  and a flag to send the unpaid invoice list with the statement.

These options aren't currently available in the library but I'll be providing a PR to fix that

**Comment by Skullbock** [comment]
Hi @GameGamer43 thanks for the PR!
I was reviewing it, but i can't seem to find where these parameters are stated in the documentation of the zoho books api (https://www.zoho.com/books/api/v3/contacts/#email-statement)

What am i missing?
Thanks!

**Comment by GameGamer43** [comment]
@Skullbock Yea, unfortunately this is something they didn't document, so we reached out on this and verified it with the Zoho Books support team. You can also see these parameters when emailing a statement in the Zoho Books API.

**Comment by Skullbock** [comment]
Classic zoho style then 🤣

**Comment by Skullbock** [comment]
Added in 5.4.1
