### ISSUE TITLE
Broken compatibility with php ^7.2

### ISSUE THREAD

**Issue by jutiss** [Weble/ZohoBooksApi#94]
Hey!

One of the latest commits [broke](https://github.com/Weble/ZohoBooksApi/commit/1831aad13fed7596a3d8e8a9bb7b014e0274c3e7#diff-b83d8002252c04942be7ab263bd48ee1d5c4ccec6aaabe759280136d78c22689R74) compatibility with php ^7.2 by adding a trailing comma after the parameter.

```php
public function emailStatement(
        $id,
        $from = null,
        $to = null,
        $data = [],
        $filterBy = 'Status.All',
        $sendUnpaidInvoiceList = false,
 ) 
```

I hope that will help find other similar issues so they can be fixed soon.
Thanks for your work!

**Comment by Skullbock** [comment]
Thanks for the notice. Can you send a quick pr to fix this issue?

Thanks

**Comment by jutiss** [comment]
Thanks for the quick response
Created a pull request
